### ISSUE TITLE
京东评论重复

### ISSUE THREAD

**Issue by edfall** [ClericPy/EC-Spider#1]
京东评论爬虫是否真实试验过，实际数据好多评论都是重复的，是否有解决方案？

**Comment by ClericPy** [comment]
新接口：http://club.jd.com/productpage/p-1150557-s-0-t-3-p-99999999.html 太久不更新了，评论一般接口是和网页上一致的

**Comment by edfall** [comment]
这个接口好像没有变吧，应该是京东反爬虫技术比较厉害了吧，很多方法已经不能使用了
