### ISSUE TITLE
京东爬虫空数据...

### ISSUE THREAD

**Issue by edfall** [ClericPy/EC-Spider#2]
是因为被服务器给墙了吧？

**Comment by ClericPy** [comment]
爬虫接口应该过期好久了。。。过段时间打算弄一套评论过滤，到时候再看下这个吧。
新接口http://club.jd.com/productpage/p-1150557-s-0-t-3-p-99999999.html 可以自己尝试下，1150557是商品ID。p后的数字是页码。
JSON.productCommentSummary.commentCount
//10就是页码总数。页码范围是 0-总数

**Comment by ClericPy** [comment]
刚才试了下，get_jd.py 还是可以用的

**Comment by edfall** [comment]
# 的确是可以用的，你可以参照我的代码：

``` python
from urllib import request
from cchardet import detect
from random import random, sample
from time import sleep
url = 'http://club.jd.com/productpage/p-1029507-s-0-t-3-p-{}.html'
data = []
null = None
false = False
true = True

def get_comments(code):
    target_url = url.format(code)
    print(target_url)
    try:
        temp = request.urlopen(target_url)
        temp_json_data = temp.read()
        json_data = temp_json_data.decode(detect(temp_json_data)['encoding'])
        if json_data:
            return json_data
        else:
            sleep(10)
            return get_comments(code)
    except:
        print('failed:{}'.format(target_url))
        return ''

for i in range(1, 1000):
    json_data = get_comments(i)
    if json_data:
        json_dict = eval(json_data)
        comments = json_dict['comments']
        data += comments
```

理论上应该获取_9990_条评论，结果只有_200_多条，其它的都是重复的....

**Comment by ClericPy** [comment]
我刚才用我过期那个代码跑了下，和网页上看基本一样的啊，重复也是他们重复的照样抓了。话说，我自己写的代码差点都看不懂了……

**Comment by edfall** [comment]
重复是因为京东后台返回数据有问题....所以通过`http://club.jd.com/productpage/p-1029507-s-0-t-3-p-{}.html`获取所有评论的方法并不可靠，抓取了大量重复的数据，压根没有一点用....

**Comment by ClericPy** [comment]
这个参考下反爬取策略试试吧，代码是2年前实习时候用的，很久没关注了，当前版本的后面参数?callback=fetchJSON_comment98vv85200 已经不是冗余的了，加和不加结果不同，有兴趣可以尝试下

**Comment by edfall** [comment]
好，看一下

**Comment by ClericPy** [comment]
刚才试了下，s-0-t-1比t-3更接近网页上看到的评论页数所对应内容，至于为什么大范围采集会造成数据缺失。。。下班再看看吧……

**Comment by ClericPy** [comment]
突然想起来。。。有没有注意到我代码里提到： 因为经常抓到空数据，所以重试20次
它有的时候是会返回空数据的，而且也给出了处理办法，因为二者的headers是不一样的，遇到这种情况多次重试就解决缺失问题了
CaseInsensitiveDict({'transfer-encoding': 'chunked', 'content-encoding': 'gzip', 'content-type': 'text/html;charset=gbk', 'server': 'JengineD', 'vary': 'Accept-Encoding', 'date': 'Tue, 15 Mar 2016 09:14:31 GMT', 'connection': 'close'})
CaseInsensitiveDict({'transfer-encoding': 'chunked', 'cache-control': 'max-age=2592000', 'content-type': 'application/json;charset=GBK', 'server': 'JengineD', 'expires': 'Wed, 24 Feb 2016 16:11:44 GMT', 'last-modified': 'Tue, 15 Mar 2016 09:14:31 GMT', 'date': 'Tue, 15 Mar 2016 09:14:31 GMT', 'connection': 'close'})

**Comment by edfall** [comment]
空代码是服务器拒绝，等一下就能获取了。京东控制了1分钟只能获取接近10次，就算不重复，直接等就好了,,！！！

**Comment by ClericPy** [comment]
好吧。。。只能代理池 队列了
