### ISSUE TITLE
请问如何爬取天猫某商品的评论

### ISSUE THREAD

**Issue by re-imagined** [ClericPy/EC-Spider#4]
似乎没找到可以直接获得所有评论的json格式的url 😢

**Comment by ClericPy** [comment]
建议掌握一下web抓包方面的知识
https://zhuanlan.zhihu.com/p/21479334
 所有评论的话很少一次得到的, 一般接口都会分页, web抓包用chrome的审查元素和火狐的firebug多数情况都可以得到

**Comment by re-imagined** [comment]
用python获取天猫源代码的时候并不能获得完整的页面内容，这样一来就不能用解析html标签的方法抓内容了

**Comment by ClericPy** [comment]
说过了学一下抓包的基础知识
或者看看我发的网址里面有关js渲染的文章,selenium和phantomjs
